Repository rauc/rauc, pull requests merged in 2018-02, with the labels that each got.

#230 README: add link to IRC and Matrix channel
  README.rst
Labels: documentation

#231 uncrustify: add configuration and helper script
  .uncrustify.cfg
  uncrustify.sh
Labels: enhancement

#232 src: replace RaucSlot mount_internal by ext_mount_point
  include/config_file.h
  src/install.c
  src/mount.c
Labels: enhancement

#229 Add sub command 'write-slot'
  docs/advanced.rst
  docs/examples.rst
  src/main.c
  test/rauc.t
Labels: enhancement

#166 Central persistent status file
  .travis.yml
  Makefile.am
  configure.ac
  docs/reference.rst
  docs/using.rst
  include/config_file.h
  include/mark.h
  src/config_file.c
  src/install.c
  src/mark.c
  src/rauc-installer.xml
  src/service.c
  test/config_file.c
  test/install.c
  test/service.c
  test/test-global.conf
Labels: enhancement

#233 Add option "--detailed" to rauc status
  docs/using.rst
  src/main.c
  test/rauc.t
Labels: enhancement

#217 Introduce casync support
  docs/advanced.rst
  docs/reference.rst
  include/bundle.h
  include/config_file.h
  src/bundle.c
  src/config_file.c
  src/install.c
  src/main.c
  src/update_handler.c
Labels: documentation, enhancement, needs-tests

#237 docs: list and reference valid 'hooks' arguments in reference.rst
  docs/reference.rst
  docs/using.rst
Labels: documentation
