Repository rauc/rauc, pull requests merged in 2018-10, with the labels that each got.

#335 test/rauc.t: check if faketime is available
  test/rauc.t
Labels: testing

#319 Bootloader Interface Fixes, Enhancements and Documentation
  docs/reference.rst
  src/bootchooser.c
  test/bootchooser.c
Labels: bug, documentation, enhancement

#340 Collection of minor doc fixes
  README.rst
  contrib/cgi/README.rst
  docs/index.rst
  docs/integration.rst
  docs/reference.rst
  docs/updating.rst
  docs/using.rst
Labels: documentation

#338 Add extra-mount-opts slot config key
  docs/reference.rst
  include/config_file.h
  include/mount.h
  src/config_file.c
  src/mount.c
  test/common.c
  test/config_file.c
Labels: enhancement

#345 Rework progress step allocation and freeing
  include/context.h
  src/context.c
  src/install.c
Labels: bug, enhancement

#328 Remove need for .raucb extension
  include/bundle.h
  include/network.h
  src/bundle.c
  src/install.c
  src/main.c
  src/network.c
  test/bundle.c
  test/network.c
  test/rauc.t
Labels: enhancement

#269 service: add system info properties
  docs/reference.rst
  src/rauc-installer.xml
  src/service.c
  test/service.c
  test/test.conf
Labels: enhancement

#344 docs: using.rst: add chapter on how to debug RAUC
  docs/using.rst
Labels: documentation

#341 More targeted debug and error messages
  src/install.c
  src/main.c
  test/install.c
  test/service.c
Labels: enhancement

#349 Fix Issues with Slot Status Over D-Bus
  src/main.c
Labels: bug

#354 test: add Dockerfile
  test/Dockerfile
Labels: testing
