Repository rauc/rauc, pull requests merged in 2018-05, with the labels that each got.

#267 Remove assertion on interfiles
  src/signature.c
  test/signature.c
Labels: bug

#268 Clarify bundle installation D-Bus API
  docs/reference.rst
  docs/using.rst
Labels: documentation, enhancement

#272 docs/integration: Corrected the UEFI system.conf example
  docs/integration.rst
Labels: bug, documentation
