Repository rauc/rauc, pull requests merged in 2018-08, with the labels that each got.

#290 elboulangero/casync extract fixes
  src/update_handler.c
Labels: bug

#296 Add fsync to copy_raw_image()
  src/update_handler.c
Labels: bug

#291 Introduce max-download-size config setting (fixes #287)
  docs/reference.rst
  include/config_file.h
  src/bundle.c
  src/config_file.c
  test/config_file.c
Labels: enhancement

#295 Advanced Testing for U-Boot and Minor Boot Selection Fixes
  src/bootchooser.c
  test/bin/fw_printenv
  test/bin/fw_setenv
  test/bootchooser.c
Labels: enhancement, testing

#304 docs: add minimal hint on --disable-service in RAUC faq
  docs/faq.rst
Labels: documentation

#274 contrib: cgi: add simple stand-alone CGI interface for RAUC
  .travis.yml
  contrib/cgi/.gitignore
  contrib/cgi/Makefile.am
  contrib/cgi/README.rst
  contrib/cgi/autogen.sh
  contrib/cgi/build-aux/git-version-gen
  contrib/cgi/configure.ac
  contrib/cgi/m4/.gitignore
  contrib/cgi/m4/ax_append_compile_flags.m4
  contrib/cgi/m4/ax_append_flag.m4
  contrib/cgi/m4/ax_append_link_flags.m4
  contrib/cgi/m4/ax_check_compile_flag.m4
  contrib/cgi/m4/ax_check_enable_debug.m4
  contrib/cgi/m4/ax_check_link_flag.m4
  contrib/cgi/m4/ax_compiler_flags.m4
  contrib/cgi/m4/ax_compiler_flags_cflags.m4
  contrib/cgi/m4/ax_compiler_flags_gir.m4
  contrib/cgi/m4/ax_compiler_flags_ldflags.m4
  contrib/cgi/m4/ax_is_release.m4
  contrib/cgi/m4/ax_require_defined.m4
  contrib/cgi/src/cgi.c
  contrib/cgi/src/rauc-installer.xml
  uncrustify.sh
Labels: enhancement

#310 Let build fail if uncrustify reports a diff
  .travis.yml
  src/config_file.c
  src/signature.c
  test/bootchooser.c
Labels: testing

#300 add support for PKCS#11 tokens
  .travis.yml
  README.rst
  configure.ac
  docs/advanced.rst
  docs/index.rst
  docs/reference.rst
  docs/using.rst
  src/main.c
  src/signature.c
  test/rauc.t
Labels: enhancement

#314 .travis.yml: re-add missing cpp-coveralls
  .travis.yml
Labels: testing

#306 src/install: Not finding an appropriate target slot must be fatal
  src/install.c
Labels: backport, bug

#309 Add Option to use Signing Time For Bundle Verification Instead of Current
  .travis.yml
  configure.ac
  docs/reference.rst
  include/config_file.h
  src/config_file.c
  src/signature.c
  test/rauc.t
Labels: enhancement

#305 src/install: actually handle readonly slots
  src/install.c
  src/main.c
  test/install.c
  test/rauc.t
Labels: bug

#308 Add Support for Verifying Signature During Bundle Creation
  docs/using.rst
  include/signature.h
  src/signature.c
  test/rauc.t
  test/signature.c
Labels: enhancement
