Repository rauc/rauc, pull requests merged in 2018-03, with the labels that each got.

#240 src/update_handler: support vfat to vfat
  src/update_handler.c
Labels: enhancement

#245 Add of required parameters to create casync bundle.
  docs/advanced.rst
Labels: documentation

#242 Add support for updating eMMC boot partitions
  Makefile.am
  README.rst
  docs/advanced.rst
  include/emmc.h
  src/emmc.c
  src/update_handler.c
Labels: enhancement

#251 Fix out-of-tree build and temporary disable coverity
  .travis.yml
  Makefile.am
Labels: bug

#239 Dbus getslotstatus entries
  include/config_file.h
  src/config_file.c
  src/main.c
  src/service.c
Labels: enhancement

#252 add barebox-statename parameter
  docs/reference.rst
  include/config_file.h
  src/bootchooser.c
  src/config_file.c
Labels: enhancement

#253 docs: fix some minor spelling errors (mostly typos)
  docs/advanced.rst
  docs/basic.rst
  docs/reference.rst
  docs/terminology.rst
  docs/using.rst
Labels: documentation
