Repository rauc/rauc, pull requests merged in 2019-03, with the labels that each got.

#420 docs: using: fix section level
  docs/using.rst
Labels: documentation

#384 src/bootchooser: added full GRUB2 support
  src/bootchooser.c
  test/bin/grub-editenv
  test/bootchooser.c
Labels: enhancement

#421 src: fix a few typos
  src/manifest.c
  src/signature.c
Labels: bug

#423 rauc.service: add documentation url
  data/rauc.service.in
Labels: documentation

#424 Check that we do not generate a bundle inside a source dir
  include/utils.h
  src/main.c
  src/utils.c
Labels: bug, enhancement

#414 .lgtm.yml: enable analysis for tests as well
  .lgtm.yml
Labels: testing

#425 Add an initial version of a man page
  Makefile.am
  rauc.1
Labels: documentation
