Repository rauc/rauc, pull requests merged in 2019-10, with the labels that each got.

#492 src/main: add help text for 'service' (if configured)
  src/main.c
Labels: bug

#434 src/main.c: A progress bar for RAUC
  src/main.c
Labels: enhancement

#485 src/install: Fix External Mount Point Handling
  src/install.c
Labels: bug

#478 src/install: check basic things before starting installation
  src/install.c
Labels: enhancement

#439 configure: refine D-Bus install directories
  .travis.yml
  Makefile.am
  README.rst
  configure.ac
  data/de.pengutronix.rauc.conf
Labels: needs rework

#495 Fix and enhance input/output path sanity checks for bundle generation
  src/main.c
Labels: bug

#477 Grouped Slot Printout for 'rauc status'
  Makefile.am
  include/config_file.h
  include/slot.h
  src/config_file.c
  src/install.c
  src/main.c
  src/service.c
  src/slot.c
  src/update_handler.c
  test/config_file.c
  test/slot.c
  test/update_handler.c
Labels: enhancement

#499 docs/integration: some clarification on grub.cfg and grubenv placement
  docs/integration.rst
Labels: documentation

#502 configure.ac: do not depend on dbus pkconfig if D-Bus is not required
  configure.ac
Labels: bug

#370 add example how to mount the correct data partition for redundant layout
  CHANGES
  docs/advanced.rst
Labels: documentation
