Repository rauc/rauc, pull requests merged in 2019-09, with the labels that each got.

#474 test/install: deactivate check that depends on GHashTable implementation
  test/install.c
Labels: bug

#476 test/install: fix test for undefined behavior in slot selection handling
  test/install.c
Labels: bug, testing

#482 keep BOOT_ACK and PARTITION_ACCESS values
  src/emmc.c
Labels: bug

#487 docs/integration: fix typo
  docs/integration.rst
Labels: documentation
