Repository rauc/rauc, pull requests merged in 2019-06, with the labels that each got.

#444 Makefile.am: add docs images and extensions dir to EXTRA_DIST
  Makefile.am
Labels: bug

#432 contrib: grub: export additional variables to environment
  contrib/grub.conf
Labels: bug

#430 Allow slot names in rauc.slot and document booted slot detection
  docs/integration.rst
  src/install.c
Labels: documentation, enhancement

#445 CHANGES: prepare for 1.1 release
  CHANGES
  docs/conf.py
Labels: documentation

#435 Atomic MBR boot partition update
  Makefile.am
  README.rst
  docs/advanced.rst
  include/config_file.h
  include/mbr.h
  include/utils.h
  src/config_file.c
  src/mbr.c
  src/update_handler.c
  src/utils.c
Labels: enhancement

#447 src/install: remove network mode
  src/install.c
  test/install.c
Labels: enhancement

#453 Fix compilation on ARM32
  src/mbr.c
  src/update_handler.c
Labels: fixed

#455 fix compile warnings/errors in src/mbr.c and endian issues
  src/mbr.c
Labels: fixed

#458 Fix test dependency handling and documentation
  README.rst
  test/rauc.t
Labels: documentation, testing
