Repository rauc/rauc, pull requests merged in 2019-01, with the labels that each got.

#367 Pass Variant and More to Hooks via Env
  docs/using.rst
  src/install.c
  src/update_handler.c
  test/update_handler.c
Labels: enhancement

#395 Fixes for external mount point detection and handling
  src/main.c
  src/service.c
Labels: bug, enhancement

#399 Collection of some documentation updates
  README.rst
  docs/integration.rst
Labels: documentation

#401 src/main: free_status_print(): free slots hash table only if existing
  src/main.c
Labels: bug

#402 Support specifying system variant via system-info handler
  src/context.c
Labels: enhancement

#404 Introduce efi-use-bootnext option to change primary-marking behavior
  docs/reference.rst
  include/config_file.h
  src/bootchooser.c
  src/config_file.c
Labels: enhancement

#381 cms_verify() directory support.
  configure.ac
  docs/advanced.rst
  docs/integration.rst
  docs/reference.rst
  include/config_file.h
  include/context.h
  src/bundle.c
  src/config_file.c
  src/context.c
  src/signature.c
  test/openssl-ca.sh
  test/openssl-ca/dir/a.cert.pem
  test/openssl-ca/dir/b.cert.pem
  test/openssl-ca/dir/hash/a/0c65607a.0
  test/openssl-ca/dir/hash/ab/0c65607a.0
  test/openssl-ca/dir/hash/ab/2c846a75.0
  test/openssl-ca/dir/index.txt
  test/openssl-ca/dir/index.txt.attr
  test/openssl-ca/dir/private/a.key.pem
  test/openssl-ca/dir/private/b.key.pem
  test/openssl-ca/dir/serial
  test/signature.c
Labels: enhancement

#400 Allow to dump signer certificate without verification
  include/bundle.h
  include/signature.h
  src/bundle.c
  src/main.c
  src/signature.c
  test/invalid-sig-bundle.raucb
  test/rauc.t
Labels: enhancement

#403 Add option for automatically resizing written ext4 images
  docs/reference.rst
  include/config_file.h
  src/config_file.c
  src/update_handler.c
  test/config_file.c
Labels: enhancement

#348 Preparations for multi-file-checksums
  include/checksum.h
  include/utils.h
  src/checksum.c
  src/manifest.c
  src/utils.c
  test/checksum.c
Labels: enhancement
