Repository rauc/rauc, pull requests merged in 2020-04, with the labels that each got.

#564 Documentation Update To Clarify and Clean Up Handler and Hook Usage
  docs/reference.rst
  docs/using.rst
Labels: documentation

#569 support --no-verify for rauc resign
  docs/advanced.rst
  rauc.1
  src/main.c
  test/rauc.t
Labels: enhancement

#575 README.rst: fix upper / lower case and typo
  README.rst
Labels: documentation

#570 add support for X.509 key usage attributes (code signing and others)
  Makefile.am
  configure.ac
  docs/advanced.rst
  docs/checklist.rst
  docs/reference.rst
  include/config_file.h
  include/signature.h
  src/bundle.c
  src/config_file.c
  src/signature.c
  test/bundle.c
  test/common.c
  test/config_file.c
  test/openssl-ca-check.sh
  test/openssl-ca-create.sh
  test/openssl-ca/dev/index.txt
  test/openssl-ca/dev/private/xku-codeSigning.pem
  test/openssl-ca/dev/private/xku-emailProtection.pem
  test/openssl-ca/dev/serial
  test/openssl-ca/dev/xku-codeSigning.cert.pem
  test/openssl-ca/dev/xku-emailProtection.cert.pem
  test/openssl-ca/manifest-cs1.sig
  test/openssl-ca/manifest-ep1.sig
  test/openssl-ca/manifest-ts1.sig
  test/openssl-ca/openssl.cnf
  test/openssl-ca/root-ca.pem
  test/openssl-ca/root/index.txt
  test/openssl-ca/root/private/xku-emailProtection.pem
  test/openssl-ca/root/private/xku-timeStamping.pem
  test/openssl-ca/root/serial
  test/openssl-ca/root/xku-timeStamping.cert.pem
Labels: enhancement

#326 allow mounted devices when using custom install handler
  docs/reference.rst
  include/slot.h
  src/config_file.c
  src/install.c
  src/update_handler.c
  test/config_file.c
  test/install-content/hook.sh
  test/install-fixtures.c
  test/install.c
  test/service.c
  test/test.conf
Labels: enhancement

#578 src/bundle: remove output files consistently on error
  src/bundle.c
Labels: bug

#446 Add new InstallBundle Method to D-Bus API
  docs/reference.rst
  docs/using.rst
  include/context.h
  include/install.h
  src/de.pengutronix.rauc.Installer.xml
  src/install.c
  src/main.c
  src/service.c
  test/service.c
Labels: enhancement

#579 improve qemu-test helper
  qemu-test
  qemu-test-init
Labels: testing

#580 use a separate travis stage for coverity
  .travis.yml
  test/get-coverity.sh
  test/run-coverity.sh
Labels: testing

#577 add a small helper script for clang's scan-build and minor fixes
  scan-build
  src/manifest.c
  src/mark.c
  test/install.c
Labels: enhancement, testing
