Repository rauc/rauc, pull requests merged in 2020-01, with the labels that each got.

#519 bundle: fix result values for error paths
  src/bundle.c
  test/bundle.c
Labels: bug

#503 src/update_handler: use g_seekable_tell() to get size of written data
  include/bundle.h
  include/checksum.h
  include/mount.h
  include/signature.h
  src/bundle.c
  src/checksum.c
  src/main.c
  src/mount.c
  src/network.c
  src/signature.c
  src/update_handler.c
  test/signature.c
Labels: bug, enhancement

#524 docs/using.rst: remove note on mandatory .raucb suffix
  docs/using.rst
Labels: documentation

#527 test/install: proper error checking in install_test_target()
  test/install.c
Labels: testing
