Repository rauc/rauc, pull requests merged in 2020-06, with the labels that each got.

#597 docs/faq: document bundle format compatibility
  docs/faq.rst
Labels: documentation

#599 docs/integration: update PTXdist section
  docs/integration.rst
Labels: documentation

#603 src/mbr: fix r_mbr_switch_set_boot_partition() error paths
  src/mbr.c
Labels: bug

#541 implement custom bootloader backend
  configure.ac
  include/config_file.h
  src/bootchooser.c
  src/config_file.c
  test/bin/custom-bootloader-script
  test/bootchooser.c
Labels: enhancement

#600 docs/integration: add custom bootloader backend description
  docs/basic.rst
  docs/integration.rst
  docs/reference.rst
Labels: documentation

#604 src/update_handler: use 256 byte inodes for ext4 by default
  CHANGES
  src/update_handler.c
  test/common.c
Labels: enhancement
