Repository rauc/rauc, pull requests merged in 2020-10, with the labels that each got.

#636 docs/reference: add missing values for system key 'bootloader'.
  docs/reference.rst
Labels: documentation

#637 Minor cleanups and test improvements
  include/bootchooser.h
  include/bundle.h
  include/checksum.h
  include/config_file.h
  include/context.h
  include/emmc.h
  include/gpt.h
  include/install.h
  include/manifest.h
  include/mark.h
  include/mbr.h
  include/mount.h
  include/network.h
  include/service.h
  include/signature.h
  include/slot.h
  include/update_handler.h
  include/utils.h
  qemu-test
  src/install.c
  src/main.c
  src/manifest.c
  src/signature.c
  test/bundle.c
  test/common.c
  test/config_file.c
  test/install-content/custom_handler.sh
  test/install-fixtures.c
  test/install.c
  test/manifest.c
Labels: testing

#647 docs/faq: document hints for using RAUC with dm-verity-protected slots
  docs/faq.rst
Labels: documentation

#629 docs: advanced: Fix Keyring move example script
  docs/advanced.rst
Labels: bug, documentation

#646 src/manifest: fix NULL pointer dereference if update_manifest fails
  src/manifest.c
  test/manifest.c
Labels: bug

#642 src/update_handler: Reorder *.img.caibx fallback handler
  src/update_handler.c
Labels: bug

#648 various cleanups
  .gitignore
  src/update_handler.c
  test/bundle.c
  test/install-fixtures.c
  test/install.c
  test/update_handler.c
Labels: enhancement, testing

#644 docs: integration: Extend description of how to set up U-Boot for RAUC
  docs/integration.rst
Labels: documentation

#634 Fix checking of remaining keys in system.conf
  include/slot.h
  src/config_file.c
  src/slot.c
Labels: bug

#628 Fix systemd D-Bus handling and RAUC error reporting
  data/rauc.service.in
  src/service.c
Labels: bug, enhancement

#625 docs: include Kernel loop device patch
  docs/integration.rst
Labels: documentation
