Repository rauc/rauc, pull requests merged in 2020-03, with the labels that each got.

#549 src/main: add missing include of string.h
  src/main.c
Labels: bug

#547 src/signature: fix error handling and memory leakage in cms_sign
  src/signature.c
Labels: bug

#536 switch CI to use QEMU instead of UML
  .travis.yml
  README.rst
  qemu-test
  qemu-test-init
Labels: testing

#550 docs/reference: clarify wording of BootSlot property contents
  docs/reference.rst
Labels: documentation

#548 src/main: the 'convert' subcommand deserves --mksquashfs-args, too.
  src/main.c
Labels: enhancement

#486 A more fancy rauc status output
  src/config_file.c
  src/main.c
Labels: enhancement

#504 install: add support for external devices
  Makefile.am
  docs/integration.rst
  include/context.h
  src/context.c
  src/install.c
  test/context.c
Labels: enhancement

#546 Allow custom casync arguments with --casync-args
  include/context.h
  src/bundle.c
  src/context.c
  src/main.c
  test/rauc.t
Labels: enhancement

#551 install dbus interface file with the correct name
  Makefile.am
  configure.ac
  contrib/cgi/Makefile.am
  contrib/cgi/src/de.pengutronix.rauc.Installer.xml
  contrib/cgi/src/rauc-installer.xml
  src/de.pengutronix.rauc.Installer.xml
Labels: enhancement

#555 disable automatic -Werror and debug mode
  .travis.yml
  configure.ac
  contrib/cgi/configure.ac
  contrib/cgi/m4/ax_is_release.m4
  m4/ax_is_release.m4
Labels: testing

#561 Allow to Enable CRL handling in RAUC's Bundle Verification
  include/config_file.h
  src/bundle.c
  src/config_file.c
  test/bundle.c
  test/rauc.t
  test/test-global.conf
  test/test.conf
Labels: enhancement

#560 Fixing a config_file test that suddenly broke..
  include/context.h
  src/context.c
  test/config_file.c
Labels: bug, testing
