Repository rauc/rauc, pull requests merged in 2020-07, with the labels that each got.

#559 Promote Central Slot Status Usage More Obviously
  docs/basic.rst
  docs/checklist.rst
  docs/reference.rst
  src/config_file.c
  test/config_file.c
Labels: documentation, enhancement

#605 Fixes and open points for custom bootloader interface
  CHANGES
  README.rst
  docs/integration.rst
  src/bootchooser.c
  src/config_file.c
  test/bootchooser.c
Labels: bug, documentation

#610 fix bundle create/resign/convert error handling
  src/bundle.c
  test/rauc.t
Labels: bug

#611 Add some testing enhancements and extend CLI testing
  qemu-test
  test/minimal-test.conf
  test/rauc.t
  test/service.c
Labels: testing

#614 fix test suite and coverage
  .gitignore
  .travis.yml
  qemu-test-init
  test/Dockerfile
  test/install-content/hook.sh
  test/rauc.t
Labels: testing

#612 Fix install printout for non-service configuration
  src/main.c
Labels: bug

#616 src/install: fix leaking gchar** with g_auto(GStrv)
  include/slot.h
  src/install.c
  src/main.c
  test/boot_switch.c
  test/update_handler.c
Labels: bug

#618 src/bootchooser: fix leaking gchar in grub_get_primary()
  src/bootchooser.c
Labels: bug
