Repository rauc/rauc, pull requests merged in 2020-11, with the labels that each got.

#649 Print signer name after verification
  include/signature.h
  src/main.c
  src/signature.c
Labels: bug, enhancement

#656 test/get-coverity: let script detect and handle errors more reliably
  test/get-coverity.sh
Labels: testing

#664 docs/integration: add links and fix typos
  docs/examples.rst
  docs/integration.rst
  docs/using.rst
Labels: documentation
