Repository rauc/rauc, pull requests merged in 2021-01, with the labels that each got.

#673 src/mount.c: fix build with kernel < 4.14
  src/mount.c
Labels: compatibility

#672 switch from Travis-CI to GitHub actions
  .github/workflows/coverity.yml
  .github/workflows/tests.yml
  .travis.yml
  Makefile.am
  configure.ac
  qemu-test
  qemu-test-init
  src/dm.c
  test/boot_switch.c
  test/dm.c
  test/get-coverity.sh
  test/rauc.t
  test/run-coverity.sh
  uml-test
  uml-test-init
Labels: testing

#675 configure.ac: increase minimum glib version required (2.49.3)
  configure.ac
Labels: compatibility

#674 Include string.h to fix Compilation With Some Toolchains
  src/dm.c
  src/signature.c
Labels: compatibility

#676 src/emmc: check the return value of g_fopen
  src/emmc.c
Labels: fixed

#677 Restore Compatibility With glib 2.50 API and add API Compatibility Checks
  configure.ac
  src/dm.c
  src/network.c
Labels: compatibility

#686 fix checksum generation in rauc convert
  configure.ac
  docs/faq.rst
  src/bundle.c
  src/mount.c
  test/bundle.c
  test/good-casync-bundle-1.4.castr/6207/620797b6a249553166433873ead3ab6aadd24e1750b3e71edd642a91c006d1d0.cacnk
  test/good-casync-bundle-1.4.castr/7f40/7f40d757cf2f63d4f32bd5b802f7bf2bafeb3d38f5f38e436ab8828f814f7d8e.cacnk
  test/good-casync-bundle-1.4.raucb
  test/good-casync-bundle-1.5.1.castr/6207/620797b6a249553166433873ead3ab6aadd24e1750b3e71edd642a91c006d1d0.cacnk
  test/good-casync-bundle-1.5.1.castr/7f40/7f40d757cf2f63d4f32bd5b802f7bf2bafeb3d38f5f38e436ab8828f814f7d8e.cacnk
  test/good-casync-bundle-1.5.1.raucb
Labels: fixed

#680 .github: workflows: compile tests on ubuntu stable releases
  .github/workflows/patches/16.04/0001-backport-to-OpenSSL-1.0.2.patch
  .github/workflows/patches/16.04/0001-src-replace-G_VARIANT_DICT_INIT-supported-not-before.patch
  .github/workflows/tests.yml
Labels: compatibility, testing

#661 Make uboot attempt settings configurable
  docs/reference.rst
  include/config_file.h
  include/utils.h
  src/bootchooser.c
  src/config_file.c
  src/utils.c
Labels: enhancement

#684 update_handler: support for nor flash devices using flashcp
  README.rst
  docs/index.rst
  docs/integration.rst
  docs/reference.rst
  qemu-test
  qemu-test-init
  src/update_handler.c
  test/update_handler.c
Labels: enhancement
