Repository rauc/rauc, pull requests merged in 2021-04, with the labels that each got.

#716 Fix configurable U-Boot attempt setting
  src/bootchooser.c
Labels: fixed

#719 Some Sanity Checks For Specifying Hooks in Bundle Manifest
  include/manifest.h
  src/bundle.c
  src/manifest.c
  test/manifest.c
Labels: bug, enhancement

#701 Make boot slot hooks more versatile
  docs/reference.rst
  src/gpt.c
  src/mbr.c
  src/update_handler.c
Labels: enhancement

#721 src/manifest: fix leaking hooks string list variables
  src/manifest.c
Labels: fixed

#723 Remove Long Deprecated Sections from Manifest Parsing.
  configure.ac
  include/manifest.h
  src/main.c
  src/manifest.c
  test/install.c
  test/manifest.c
  test/manifest.raucm
Labels: cleanup, fixed

#725 src/update_handler: generate only valid vfat label names
  src/update_handler.c
Labels: fixed
