Repository rauc/rauc, pull requests merged in 2021-07, with the labels that each got.

#751 src/bootchooser: handle external dtb also in barebox_state_set()
  src/bootchooser.c
Labels: fixed

#752 src/install: remove trailing whitespace from RAUC_SLOTS and RAUC_TARGET_SLOTS
  src/install.c
Labels: cleanup

#750 add infrastructure for streaming tests
  .gitignore
  qemu-test-init
  test/good-verity-bundle.raucb
  test/nginx.conf
  test/nginx.htpasswd
  test/nginx_backend.py
  test/openssl-ca-create.sh
  test/openssl-ca/openssl.cnf
  test/openssl-ca/root/index.txt
  test/openssl-ca/root/serial
  test/openssl-ca/web/ca.cert.pem
  test/openssl-ca/web/client-1.cert.pem
  test/openssl-ca/web/crl.pem
  test/openssl-ca/web/index.txt
  test/openssl-ca/web/index.txt.attr
  test/openssl-ca/web/private/ca.key.pem
  test/openssl-ca/web/private/client-1.pem
  test/openssl-ca/web/private/server.pem
  test/openssl-ca/web/serial
  test/openssl-ca/web/server.cert.pem
  test/openssl-ca/web/server.chain.pem
Labels: testing

#753 build the ci container via github actions and prepare for streaming tests
  .github/workflows/container.yml
  test/Dockerfile
  test/openssl-ca/web-ca.pem
Labels: testing

#754 README.rst: add CII Best Practices badge
  README.rst
Labels: documentation

#757 Check For Valid Slot Type Configuration
  include/bootchooser.h
  include/config_file.h
  include/slot.h
  src/bootchooser.c
  src/config_file.c
  src/slot.c
  test/config_file.c
Labels: enhancement

#756 change CI container repository and clean up configure.ac
  .github/workflows/coverity.yml
  .github/workflows/tests.yml
  configure.ac
Labels: cleanup

#749 feature: extract signatue: add option to extract signature from bundle
  docs/reference.rst
  include/bundle.h
  src/bundle.c
  src/main.c
  test/bundle.c
  test/rauc.t
Labels: enhancement
