Repository rauc/rauc, pull requests merged in 2022-01, with the labels that each got.

#820 src/bundle: download temporary bundle to a separate temp directory
  src/bundle.c
Labels: fixed

#822 Documentation: Copyright Update and Sphinx Cleanup
  docs/RAUC_Logo_outline.svg
  docs/conf.py
  docs/favicon.ico
Labels: documentation

#823 docs/advanced: fix script URL
  docs/advanced.rst
Labels: documentation

#826 README.rst: testing: remove instruction to run make check
  README.rst
Labels: documentation

#825 src/update_handler: add support for jffs2 tar archives
  README.rst
  include/config_file.h
  src/config_file.c
  src/mount.c
  src/update_handler.c
Labels: enhancement

#828 .github: workflows: drop support for Ubuntu 16.04 (Xenial)
  .github/workflows/patches/16.04/0001-backport-to-OpenSSL-1.0.2.patch
  .github/workflows/patches/16.04/0001-src-replace-G_VARIANT_DICT_INIT-supported-not-before.patch
  .github/workflows/tests.yml
Labels: testing

#827 fix unused variables and a missing field initializer
  src/bootchooser.c
  src/service.c
  test/update_handler.c
Labels: fixed

#462 introduce enum to tweak verification during bundle resigning
  include/bundle.h
  include/utils.h
  rauc.1
  src/bundle.c
  src/install.c
  src/main.c
  src/service.c
  src/signature.c
  test/bundle.c
  test/rauc.t
  test/update_handler.c
Labels: enhancement

#770 src: introduce --trust-environment option for 'rauc convert'
  include/bundle.h
  rauc.1
  src/bundle.c
  src/main.c
Labels: enhancement

#613 Rework parts of context and config handling for more targeted error handling.
  include/config_file.h
  include/context.h
  src/config_file.c
  src/context.c
  src/main.c
  src/service.c
  test/service.c
Labels: enhancement

#645 src/service: return D-Bus error if slot states cannot be determined
  src/install.c
  src/service.c
  test/install.c
  test/service.c
Labels: bug

#681 Fix and Improve Error Handling for resolve_loop_device()
  src/install.c
  test/install.c
Labels: fixed

#762 src/update_handler: copy_raw_image() close out_fd in case of failure
  src/update_handler.c
Labels: fixed

#747 Support SquashFS compressed bundles on poky
  src/update_handler.c
Labels: enhancement

#760 feature: replace-signature: add command to replace bundle signature
  configure.ac
  docs/reference.rst
  include/bundle.h
  src/bundle.c
  src/main.c
  test/bundle.c
  test/rauc.t
Labels: enhancement, needs rework

#832 src/service: add missing line break in g_printerr() call
  src/service.c
Labels: fixed

#831 CHANGES: prepare for 1.6 release
  CHANGES
Labels: documentation
