Repository rauc/rauc, pull requests merged in 2022-06, with the labels that each got.

#915 docs: fix broken links to GLib/U-Boot docs
  docs/integration.rst
  docs/using.rst
Labels: documentation

#916 CHANGES: prepare for 1.7 release
  CHANGES
Labels: documentation

#920 src/nbd: no need to retry if we received a 404 from the server
  src/nbd.c
Labels: enhancement

#923 README, docs/integration: be explicit that kernel modules are sufficient
  README.rst
  docs/integration.rst
Labels: documentation

#817 Initial desync support
  docs/reference.rst
  include/config_file.h
  src/bundle.c
  src/config_file.c
  src/update_handler.c
  test/config_file.c
  test/minimal-desync-test.conf
  test/rauc.t
Labels: enhancement, casync

#918 atomic bootloader update for SoCs with redundant copy support
  Makefile.am
  docs/advanced.rst
  docs/reference.rst
  include/slot.h
  include/utils.h
  src/config_file.c
  src/mbr.c
  src/slot.c
  src/update_handler.c
  src/utils.c
  test/boot_raw_fallback.c
  test/common.c
  test/common.h
  test/update_handler.c
Labels: enhancement

#931 docs/integration: add a hint to specifiy the file used to store GRUB env
  docs/integration.rst
Labels: documentation

#932 test: remove occurrences of obsolete 'archive' from [keyring] sections
  test/broken-manifest.raucm
  test/openssl-ca-check.sh
  test/openssl-ca/manifest
  test/openssl-ca/manifest-a1.sig
  test/openssl-ca/manifest-a2.sig
  test/openssl-ca/manifest-cs1.sig
  test/openssl-ca/manifest-ep1.sig
  test/openssl-ca/manifest-r1.sig
  test/openssl-ca/manifest-ts1.sig
  test/openssl-ca/manifest.mail
Labels: testing, cleanup
