Repository rauc/rauc, pull requests merged in 2022-08, with the labels that each got.

#941 fix stable CI builds
  .github/workflows/tests.yml
Labels: testing

#945 src/signature: get key passphrase from environment
  configure.ac
  docs/advanced.rst
  docs/reference.rst
  rauc.1
  src/signature.c
  test/openssl-ca-create.sh
  test/openssl-ca/rel/private/release-1-encrypted.pem
  test/rauc.t
Labels: enhancement

#936 add support for incremental updates via block hash index
  Makefile.am
  configure.ac
  docs/advanced.rst
  docs/integration.rst
  docs/reference.rst
  include/hash_index.h
  include/update_handler.h
  include/utils.h
  qemu-test-rauc-config
  src/bundle.c
  src/hash_index.c
  src/signature.c
  src/update_handler.c
  src/utils.c
  test/hash_index.c
  test/install.c
  test/test-datadir.conf
  test/update_handler.c
Labels: enhancement

#946 manifest: ignore meta.<label> sections in the manifest
  docs/reference.rst
  src/manifest.c
  test/manifest.c
Labels: enhancement

#890 Make Error Message Handling OpenSSL 3.0-Compatible
  src/signature.c
Labels: compatibility

#948 mount: remove use of sudo when running as non-root
  include/mount.h
  src/mount.c
  test/common.c
  test/install-content/custom_handler.sh
Labels: cleanup

#950 test/nginx_backend: avoid DeprecationWarning when changing application state
  test/nginx_backend.py
Labels: testing, fixed

#949 test/update_handler: do not fail when sum_target_written is zero
  test/update_handler.c
Labels: testing

#951 src/update_handler: unconditionally avoid fallback for boot-emmc
  src/update_handler.c
Labels: fixed

#947 CHANGES: prepare for 1.8 release
  CHANGES
  docs/advanced.rst
Labels: documentation

#956 Collection of (verity-related) test suite fixes
  configure.ac
  test/install-content/manifest.raucm
  test/install-content/space-dummy
  test/rauc.t
Labels: testing

#955 doc: basic notes on how to partition storage properly
  docs/advanced.rst
  docs/integration.rst
Labels: documentation

#954 Improve boot selection error messages and scoping
  src/bootchooser.c
  src/main.c
  src/mark.c
Labels: cleanup

#961 test/update_handler: be less strict with sum_source
  test/update_handler.c
Labels: testing, fixed

#958 src/context: create the data directory on startup
  src/context.c
Labels: fixed

#962 src: obtain error from errno if g_mkdir_with_parents() fails
  src/bundle.c
  src/context.c
  src/mount.c
  src/slot.c
Labels: enhancement
