Repository rauc/rauc, pull requests merged in 2022-11, with the labels that each got.

#1001 fix sporadic device mapper test failures
  test/dm.c
Labels: testing, fixed

#1017 docs: improve bootloader update documentation
  docs/advanced.rst
  docs/examples.rst
  docs/faq.rst
  docs/scenarios.rst
  docs/using.rst
Labels: documentation

#1018 docs: document our approach to bundle compatibility
  docs/advanced.rst
  docs/basic.rst
  docs/faq.rst
Labels: documentation, compatibility

#997 test/stats: make tests involving floating point calculations more lax
  test/stats.c
Labels: testing
