Repository rauc/rauc, pull requests merged in 2022-03, with the labels that each got.

#871 Fix Some Memory Leaks
  src/bundle.c
  src/config_file.c
  src/context.c
  src/manifest.c
  src/signature.c
  src/utils.c
  test/signature.c
Labels: fixed

#872 fix leaks of CMS_ContentInfo
  src/bundle.c
  src/signature.c
Labels: fixed

#878 Minor documentation updates for streaming and storage support
  README.rst
  docs/basic.rst
  docs/index.rst
  docs/integration.rst
Labels: documentation

#879 Collection of mostly signature-related fixes
  include/signature.h
  src/bundle.c
  src/signature.c
Labels: fixed

#874 (Re)Fix two Coverity-reported defects
  src/stats.c
  src/utils.c
Labels: fixed

#883 test/Dockerfile: Install Desync
  test/Dockerfile
Labels: testing

#882 add support for a list of optional incremental methods
  docs/reference.rst
  include/manifest.h
  src/main.c
  src/manifest.c
  test/install.c
  test/manifest.c
Labels: enhancement

#885 src/bundle: explicitly reject remote bundles in check_bundle_payload()
  src/bundle.c
Labels: fixed

#889 Collection of Various Fixes
  data/rauc.service.in
  src/main.c
  src/mount.c
  src/signature.c
Labels: fixed, cleanup
