Repository rauc/rauc, pull requests merged in 2022-09, with the labels that each got.

#972 src/mbr: skip empty partitions in is_region_free() check
  src/mbr.c
  test/boot_switch.c
Labels: fixed

#964 Readme.rst: link to matrix.to instead of app.element.io
  README.rst
Labels: documentation

#963 README.rst: consolidate filesystem support list
  README.rst
Labels: documentation

#957 Add casync tests and remove 'experimental' note from docs
  configure.ac
  docs/advanced.rst
  qemu-test-init
  src/bundle.c
  src/update_handler.c
  test/good-casync-bundle-verity.castr/6207/620797b6a249553166433873ead3ab6aadd24e1750b3e71edd642a91c006d1d0.cacnk
  test/good-casync-bundle-verity.castr/7f40/7f40d757cf2f63d4f32bd5b802f7bf2bafeb3d38f5f38e436ab8828f814f7d8e.cacnk
  test/good-casync-bundle-verity.raucb
  test/rauc.t
  test/update_handler.c
Labels: casync

#976 src/bundle: do not attempt to take ownership if running as non-root
  src/bundle.c
Labels: enhancement

#977 src/update_handler: unmount seed also on casync error
  src/update_handler.c
Labels: fixed

#981 docs/index: mention rauc-hawkbit-updater instead of rauc-hawkbit
  docs/index.rst
Labels: documentation

#982 CHANGES: prepare for 1.8 release
  CHANGES
Labels: documentation

#984 fix distcheck tests
  .github/workflows/distcheck.yml
  Makefile.am
  configure.ac
  test/rauc.t
Labels: testing
