Repository rauc/rauc, pull requests merged in 2022-04, with the labels that each got.

#893 src/bundle: don't let existing bundles disappear
  src/bundle.c
Labels: fixed

#895 add build test on ubuntu 21.10
  .github/workflows/tests.yml
Labels: testing

#896 docs/scenarios: remove bootname for rescue slot in additinal rescue slot
  docs/scenarios.rst
Labels: documentation

#899 docs/reference: fix InstallBundle() D-Bus method prototype
  docs/reference.rst
Labels: documentation

#900 README.rst: add required kernel options for streaming and encryption
  README.rst
Labels: documentation

#901 CHANGES: prepare for 1.7 release
  CHANGES
Labels: documentation

#902 update documentation on functionality that is out-of-scope
  docs/index.rst
Labels: documentation
