Repository rauc/rauc, pull requests merged in 2022-07, with the labels that each got.

#906 stats: add g_autoptr support, label property and some testing helpers
  Makefile.am
  include/stats.h
  src/nbd.c
  src/stats.c
  test/stats.c
Labels: enhancement, testing

#934 src/update_handler: remove debug message in vfat_label_generator
  src/update_handler.c
Labels: fixed

#935 improve stats messages
  src/nbd.c
  src/stats.c
Labels: cleanup

#937 minor fixes
  src/update_handler.c
  src/utils.c
Labels: fixed

#925 add support for a shared data directory
  docs/reference.rst
  include/config_file.h
  include/slot.h
  src/config_file.c
  src/slot.c
Labels: enhancement

#940 Fix Typos in Documentation
  docs/reference.rst
Labels: documentation
