Repository rauc/rauc, pull requests merged in 2022-02, with the labels that each got.

#842 src/bundle: fix rauc convert for empty filename
  src/bundle.c
Labels: fixed

#843 src/context: always set context configpath when config is used
  src/context.c
Labels: fixed

#844 src/install: fix error indicator init in determine_boot_states()
  src/install.c
Labels: fixed

#845 Add scan-build Actions workflow
  .github/workflows/scan-build.yml
  src/context.c
Labels: testing

#849 src/bundle: remove unused function extract_file_from_bundle()
  include/bundle.h
  src/bundle.c
  test/bundle.c
Labels: cleanup

#852 docs/reference: fix broken link
  docs/reference.rst
Labels: documentation, fixed

#855 docs/index.rst: mention Buildroot support for RAUC
  docs/images/buildroot_logo.png
  docs/index.rst
Labels: documentation

#857 Test Suite Adaptions
  README.rst
  test/network.c
  test/rauc.t
Labels: testing

#638 More usage-friendly and explicitly-handled error and info printouts for 'rauc status' (subcommands)
  Makefile.am
  configure.ac
  src/main.c
Labels: enhancement

#860 minor improvements as preparation for HTTP streaming
  .github/workflows/tests.yml
  CHANGES
  configure.ac
  qemu-test
Labels: enhancement

#755 add HTTP streaming support
  CHANGES
  Makefile.am
  configure.ac
  docs/advanced.rst
  docs/basic.rst
  docs/integration.rst
  docs/reference.rst
  docs/using.rst
  include/bundle.h
  include/config_file.h
  include/install.h
  include/nbd.h
  include/stats.h
  include/utils.h
  qemu-test-init
  src/bundle.c
  src/config_file.c
  src/install.c
  src/main.c
  src/nbd.c
  src/service.c
  src/stats.c
  src/utils.c
  test/bundle.c
  test/nbd.c
  test/rauc.t
Labels: enhancement

#865 docs/integration: mention CONFIG_CRYPTO_SHA256 in the format migration section
  docs/integration.rst
Labels: documentation, fixed

#868 src/bootchooser: fix pair of memory leaks
  src/bootchooser.c
Labels: fixed
