Repository rauc/rauc, pull requests merged in 2023-03, with the labels that each got.

#1080 refactor config file parsing and fix memory leak in slot handling
  src/config_file.c
  src/slot.c
Labels: cleanup

#1081 minor cleanups
  src/config_file.c
  src/install.c
Labels: cleanup

#1078 Fix number format handling for U-Boot
  contrib/uboot.sh
  src/bootchooser.c
  test/bootchooser.c
Labels: fixed

#1073 docs: meson.build: add input files as build dependencies
  docs/meson.build
Labels: needs rework, documentation, build

#1082 src/install: support resolving partitioned loop devices
  src/install.c
Labels: fixed

#1084 meson.build: support generating version information from git
  meson.build
  version-gen
  version.h.in
Labels: build

#1088 meson.build: install man page
  .github/workflows/tests.yml
  meson.build
Labels: build

#1095 Add support for FTPS
  src/bundle.c
Labels: enhancement

#1092 src: give check_slot low progress weight
  include/context.h
  src/context.c
  src/install.c
  test/service.c
Labels: enhancement

#1093 Emitting Fine-Grained Progress over D-Bus for Most Update Handler (Rework)
  src/update_handler.c
  test/service.c
  test/update_handler.c
Labels: enhancement

#1098 Extend tested distros
  .github/workflows/tests.yml
Labels: testing

#1099 src/manifest: fix memory leak
  src/manifest.c
Labels: fixed
