Repository rauc/rauc, pull requests merged in 2023-08, with the labels that each got.

#1198 CHANGES: prepare for 1.10.1 release
  CHANGES
Labels: documentation

#1197 Fix bootchooser for the output of efibootmgr 18
  include/utils.h
  src/bootchooser.c
  src/config_file.c
  src/utils.c
  test/config_file.c
Labels: compatibility

#1204 CHANGES: prepare for 1.10.1 release
  CHANGES
  meson.build
Labels: documentation

#1152 Add System Information HTTP Headers
  docs/advanced.rst
  docs/reference.rst
  include/bundle.h
  include/config_file.h
  include/install.h
  include/nbd.h
  src/bundle.c
  src/config_file.c
  src/install.c
  src/nbd.c
  test/config_file.c
Labels: enhancement

#1206 Minor test improvements and leak fixes
  qemu-test
  qemu-test-init
  src/service.c
  test/boot_raw_fallback.c
  test/boot_switch.c
  test/bootchooser.c
  test/bundle.c
  test/checksum.c
  test/manifest.c
  test/nbd.c
  test/network.c
  test/progress.c
  test/service.c
  test/signature.c
  test/slot.c
  test/stats.c
  test/update_handler.c
  test/utils.c
Labels: testing

#1208 test: meson.build: increase timeout for sharness tests by 1 minute
  test/meson.build
Labels: testing

#1158 Ensure Consistent Slot Status
  src/config_file.c
  src/install.c
Labels: enhancement

#1160 Introduce System Status and Use For Boot Detection
  .github/workflows/sanitizers.yml
  Makefile.am
  include/config_file.h
  include/context.h
  include/status_file.h
  meson.build
  src/config_file.c
  src/context.c
  src/install.c
  src/main.c
  src/mark.c
  src/service.c
  src/status_file.c
  test/config_file.c
  test/meson.build
  test/status_file.c
Labels: enhancement

#1211 README: clarify license
  README.rst
Labels: documentation

#1213 .gitignore: add bzImage
  .gitignore
Labels: cleanup

#1214 src/install: fix error handling on status write failure during slot update failure
  src/install.c
Labels: fixed

#1212 src/manifest: ignore new per-image keys version, description and build
  src/manifest.c
  test/manifest.c
Labels: enhancement

#1217 Make marking interface more consistent
  include/mark.h
  src/install.c
  src/mark.c
Labels: cleanup

#1222 update_utils: make copy_with_progress reusable
  Makefile.am
  include/update_utils.h
  meson.build
  src/update_handler.c
  src/update_utils.c
Labels: cleanup

#1225 create links to active slot devices in /run/rauc/slots/active
  docs/using.rst
  qemu-test-init
  src/main.c
  test/rauc.t
Labels: enhancement

#1227 add opengraph sphinx extension for social media preview
  .readthedocs.yaml
  docs/conf.py
  docs/requirements.txt
  test/Dockerfile
Labels: documentation

#1229 test/Dockerfile: remove python3-sphinxext-opengraph for now
  test/Dockerfile
Labels: documentation, testing

#1231 test/Dockerfile: pin desync to version 0.9.3
  test/Dockerfile
Labels: testing

#1228 docs/conf.py: make opengraph optional and use sphinx_rtd_theme for local builds as well
  docs/conf.py
  docs/requirements.in
  docs/requirements.txt
Labels: documentation

#1232 Expose transaction ID to pre/post install handlers
  docs/reference.rst
  src/install.c
  test/bin/postinstall.sh
  test/bin/preinstall.sh
Labels: enhancement

#1233 Add libFuzzer setup
  .github/workflows/tests.yml
  fuzz/bundle.c
  fuzz/manifest.c
  fuzz/manifest.dict
  fuzz/meson.build
  meson.build
  meson_options.txt
  uncrustify.sh
Labels: testing

#1239 src/main: more user-friendly output when no slot is activated
  src/main.c
Labels: enhancement

#1238 Fix Arithmetic exception on Zero-sized images + Error Propagation Fix
  src/update_handler.c
  src/update_utils.c
Labels: fixed

#1240 add meson wrap files for glib, json-glib and openssl
  subprojects/glib.wrap
  subprojects/json-glib.wrap
  subprojects/openssl.wrap
Labels: testing

#1241 src: detect config file change and warn in service log
  include/config_file.h
  src/config_file.c
  src/service.c
Labels: enhancement
