Repository rauc/rauc, pull requests merged in 2023-05, with the labels that each got.

#1106 Add perform-pre-check configuration option
  .uncrustify.cfg
  docs/reference.rst
  include/config_file.h
  src/bundle.c
  src/config_file.c
  src/nbd.c
  src/update_handler.c
  test/boot_raw_fallback.c
  test/bundle.c
  test/common.c
  test/common.h
  test/dm.c
Labels: enhancement

#1116 minor fixes for docs/reference
  docs/reference.rst
Labels: documentation

#1117 src/bundle: allow exFAT as local file system
  src/bundle.c
Labels: enhancement

#1122 test/common: convert to g_autofree for strings
  test/common.c
Labels: cleanup

#1123 src/bundle: ensure that the output directory does not exist before extracting
  src/bundle.c
Labels: fixed

#1115 Refactor and Extend `system-info` Handler to Obtain Generic System Information
  docs/reference.rst
  docs/using.rst
  include/context.h
  include/utils.h
  rauc.1
  src/bundle.c
  src/context.c
  src/install.c
  src/main.c
  src/manifest.c
  src/update_handler.c
  test/bin/systeminfo.sh
  test/config_file.c
  test/context.c
  test/install.c
  test/service.c
Labels: cleanup

#1127 .github/workflows: update to actions/checkout@v3
  .github/workflows/container.yml
  .github/workflows/coverity.yml
  .github/workflows/distcheck.yml
  .github/workflows/scan-build.yml
  .github/workflows/tests.yml
Labels: testing

#1126 fix some leaks and add a address-sanitizer workflow
  .github/workflows/sanitizers.yml
  src/context.c
  test/bundle.c
  test/checksum.c
  test/manifest.c
  test/network.c
  test/slot.c
Labels: testing, fixed

#1131 .github: workflows: tests: test building against older debian releases
  .github/workflows/tests.yml
Labels: testing

#1133 docs: clarify streaming build-time option
  docs/advanced.rst
  docs/basic.rst
Labels: documentation

#1141 point to distribution packages in the integration chapter and in the README
  README.rst
  docs/integration.rst
Labels: documentation

#1128 fix memory leaks found by address sanitizer and enable more tests
  .github/workflows/sanitizers.yml
  src/bootchooser.c
  src/config_file.c
  src/context.c
  test/boot_switch.c
  test/config_file.c
  test/nbd.c
Labels: testing, fixed

#1125 recommend verity bundles by default
  docs/reference.rst
  include/manifest.h
  src/bundle.c
  src/manifest.c
  test/manifest.c
Labels: enhancement, documentation
