Repository rauc/rauc, pull requests merged in 2023-01, with the labels that each got.

#1033 Fix minor issues found by CodeQL
  src/hash_index.c
  test/network.c
Labels: fixed

#1026 manifest: parse and store metadata
  docs/reference.rst
  include/manifest.h
  src/manifest.c
  test/manifest.c
Labels: enhancement

#1034 CI: fix (armel) cross build
  .github/workflows/tests.yml
Labels: testing, external bug

#1042 README.rst: note build dependency on libnl-genl-3-dev for streaming
  README.rst
Labels: documentation

#1037 Check image size before starting installation
  include/utils.h
  src/update_handler.c
  src/utils.c
  test/update_handler.c
  test/utils.c
Labels: fixed

#1021 Add Meson Build Support
  .github/workflows/coverity.yml
  .github/workflows/scan-build.yml
  .github/workflows/tests.yml
  README.rst
  data/meson.build
  docs/meson.build
  meson.build
  meson_options.txt
  qemu-test
  qemu-test-init
  scan-build
  scan-build-wrapper.sh
  src/update_handler.c
  test/Dockerfile
  test/meson.build
  test/rauc.t
Labels: testing, build

#1039 src/nbd: be lenient with libcurl without proxy support
  src/nbd.c
Labels: compatibility

#1049 .github: workflows: coverity: use meson build command
  .github/workflows/coverity.yml
Labels: testing

#1050 README.rst: Some Updates To Updates Scopes and Add Features
  README.rst
Labels: documentation

#1053 docs/advanced: p11tool is provided by GnuTLS
  docs/advanced.rst
Labels: documentation
