Repository rauc/rauc, pull requests merged in 2023-07, with the labels that each got.

#1178 configure.ac: fix help text name of --with-streaming_user
  configure.ac
Labels: build

#1180 Fix some leaks revealed when running sharness test with adress sanitizer
  src/context.c
  src/manifest.c
  src/signature.c
Labels: fixed

#1179 Fix leaks and enable address sanitizer for install-test
  .github/workflows/sanitizers.yml
  src/config_file.c
  src/install.c
  src/manifest.c
  test/install-fixtures.c
  test/install.c
Labels: testing

#1184 meson.build: fix dbus default directories
  meson.build
Labels: fixed

#1188 README.rst: document 'ninja -C build' alternative to 'meson compile -C build'
  README.rst
Labels: documentation

#1192 docs/faq: document possible filesystem incompatibility with ext4
  docs/faq.rst
Labels: documentation

#1183 get_system_info_from_handler: do not step on existing values
  Makefile.am
  configure.ac
  src/context.c
  test/context.c
  test/test-dummy-handler.conf
Labels: bug
