Repository rauc/rauc, pull requests merged in 2023-11, with the labels that each got.

#1269 meson: add htmldocs option for installing the docs
  .github/workflows/tests.yml
  docs/meson.build
  meson_options.txt
Labels: documentation

#1276 Add 'crypt' Bundle Support to 'resign' and 'replace-signature' Subcommands
  src/bundle.c
  test/rauc.t
Labels: enhancement, fixed

#1273 utils: add fakeroot helpers
  include/utils.h
  src/utils.c
  test/utils.c
Labels: enhancement

#1278 qemu-test-init: add an ll alias for ls -l
  qemu-test-init
Labels: testing

#1280 simplify subprocess handling
  include/utils.h
  src/bundle.c
  src/mount.c
  src/update_handler.c
  src/utils.c
Labels: cleanup

#1282 fix resource leaks and return value checks
  src/utils.c
  test/event-log.c
Labels: fixed

#1281 qemu-test: allow specifiying test to run
  qemu-test
  qemu-test-init
Labels: testing

#1286 List Available Format Options for `rauc info` and `rauc status`
  docs/using.rst
  src/main.c
Labels: documentation

#1284 docs/using: be more specific about how hooks work
  docs/using.rst
Labels: documentation
