Repository rauc/rauc, pull requests merged in 2023-10, with the labels that each got.

#1257 requirements.txt: update to current versions
  docs/requirements.txt
Labels: documentation, dependencies

#1230 Configurable Event Logging
  Makefile.am
  docs/advanced.rst
  docs/reference.rst
  include/config_file.h
  include/event_log.h
  meson.build
  qemu-test-rauc-config
  src/config_file.c
  src/context.c
  src/event_log.c
  src/main.c
  test/config_file.c
  test/event-log.c
  test/meson.build
Labels: enhancement

#1258 Fix installation of rauc.1 manpage
  meson.build
Labels: build

#1259 .github: workflows: coverity: disable git unsafe directory check
  .github/workflows/coverity.yml
Labels: testing

#1260 .github/workflows/tests: switch to official multiarch Debian containers
  .github/workflows/tests.yml
Labels: testing, fixed

#1262 Fixes for Event Logging (Static Code Analysis)
  .github/workflows/sanitizers.yml
  src/config_file.c
  src/event_log.c
  test/event-log.c
Labels: testing, fixed

#1261 Remove Autotools Support
  .github/workflows/codeql.yml
  .github/workflows/distcheck.yml
  .github/workflows/tests.yml
  .gitignore
  .lgtm.yml
  Makefile.am
  README.rst
  autogen.sh
  configure.ac
  contrib/cgi/autogen.sh
  contrib/cgi/m4/.gitignore
  contrib/cgi/m4/ax_append_compile_flags.m4
  contrib/cgi/m4/ax_append_flag.m4
  contrib/cgi/m4/ax_append_link_flags.m4
  contrib/cgi/m4/ax_check_compile_flag.m4
  contrib/cgi/m4/ax_check_enable_debug.m4
  contrib/cgi/m4/ax_check_link_flag.m4
  contrib/cgi/m4/ax_compiler_flags.m4
  contrib/cgi/m4/ax_compiler_flags_cflags.m4
  contrib/cgi/m4/ax_compiler_flags_gir.m4
  contrib/cgi/m4/ax_compiler_flags_ldflags.m4
  contrib/cgi/m4/ax_require_defined.m4
  docs/advanced.rst
  docs/basic.rst
  docs/contributing.rst
  docs/faq.rst
  docs/integration.rst
  docs/reference.rst
  docs/release-checklist.txt
  docs/using.rst
  m4/.gitignore
  m4/ax_append_compile_flags.m4
  m4/ax_append_flag.m4
  m4/ax_append_link_flags.m4
  m4/ax_check_compile_flag.m4
  m4/ax_check_enable_debug.m4
  m4/ax_check_link_flag.m4
  m4/ax_code_coverage.m4
  m4/ax_compiler_flags.m4
  m4/ax_compiler_flags_cflags.m4
  m4/ax_compiler_flags_gir.m4
  m4/ax_compiler_flags_ldflags.m4
  m4/ax_require_defined.m4
  m4/ax_valgrind_check.m4
  src/bundle.c
  test/Dockerfile
  test/service.c
Labels: build

#1271 docs/integration: recommend using stable paths in fstab and system.conf
  docs/integration.rst
Labels: documentation

#1272 update python requirements for docs and add helper
  docs/requirements.txt
  docs/update-requirements.sh
Labels: documentation

#1274 include/utils: simplify inline functions using g_autofree
  include/utils.h
Labels: cleanup
