Repository rauc/rauc, pull requests merged in 2023-06, with the labels that each got.

#1150 src: add installation transaction UUID
  docs/reference.rst
  include/install.h
  include/slot.h
  rauc.1
  src/config_file.c
  src/install.c
  src/main.c
  src/service.c
  src/slot.c
Labels: enhancement

#1144 src/main: add missing --key argument for 'rauc info'
  rauc.1
  src/bundle.c
  src/main.c
Labels: fixed

#1145 src/install: fix broken plan installation failure handling
  src/install.c
Labels: fixed

#1151 Obtain system's boot ID and machine ID
  include/context.h
  src/context.c
Labels: enhancement

#1143 fix memory leaks found by address sanitizer and enable even more tests
  .github/workflows/sanitizers.yml
  configure.ac
  include/slot.h
  meson.build
  qemu-test-init
  src/bootchooser.c
  src/context.c
  src/install.c
  src/slot.c
  test/bundle.c
  test/common.c
  test/common.h
  test/install-fixtures.c
  test/install.c
  test/nbd.c
  test/service.c
  test/signature.c
Labels: testing, fixed

#1159 fix memory leaks found by address sanitizer and enable it for update_handler tests
  .github/workflows/sanitizers.yml
  src/bundle.c
  src/update_handler.c
  test/update_handler.c
Labels: fixed

#1163 src/bundle: fix read size for read_complete_dm_device
  src/bundle.c
Labels: fixed

#1166 data: meson.build: install rauc-service.sh with executable bit set
  data/meson.build
Labels: fixed, build

#1162 src/nbd: use a shorter connect timeout
  src/nbd.c
Labels: enhancement

#1153 Cleanup, Refactoring and Fixes For Installation Handling and Slot Marking
  include/mark.h
  src/install.c
  src/mark.c
Labels: fixed, cleanup

#1169 check return values of lstat and g_setenv in the test suite
  test/bootchooser.c
  test/utils.c
Labels: testing

#1171 src/hash_index: initialize 'middle' for consistency
  src/hash_index.c
Labels: fixed

#1172 src/dm: remove fallback implementation of g_uuid_string_random()
  src/dm.c
Labels: cleanup

#1174 CHANGES: minor fixes
  CHANGES
Labels: documentation
