Repository rauc/rauc, pull requests merged in 2023-04, with the labels that each got.

#1104 src/install: fix string memory leaks
  src/install.c
Labels: fixed

#1105 src/install: un-break external mount point detection
  src/install.c
  test/install.c
Labels: bug

#1108 src/service: do not configure context twice
  src/service.c
Labels: cleanup

#1109 utils: add helper to atomically update symlinks
  include/utils.h
  src/utils.c
  test/utils.c
Labels: enhancement

#1107 Rework Parts of Slot State Determination
  include/config_file.h
  include/install.h
  src/context.c
  src/install.c
  src/main.c
  src/service.c
  test/context.c
  test/install.c
  test/rauc.t
Labels: cleanup

#1110 minor fixes (leaks and typo)
  include/slot.h
  src/main.c
  test/slot.c
Labels: fixed

#1102 Amend Description of Key ``statusfile``
  docs/reference.rst
Labels: documentation
