Repository rauc/rauc, pull requests merged in 2023-12, with the labels that each got.

#1290 README.rst: add repology overview image
  README.rst
Labels: documentation

#1283 test/service: simplify service fixture setup
  test/service.c
Labels: testing, cleanup

#1288 test/common: add test_lstat helper
  test/common.c
  test/common.h
Labels: enhancement, testing

#1291 contrib/uboot.sh: add note to explain that it needs to be adjusted to the use-case
  contrib/uboot.sh
Labels: documentation

#1295 Fixes typo in documentation
  docs/examples.rst
Labels: documentation

#1298 add note about NBD netlink API requirement
  docs/integration.rst
Labels: documentation

#1296 prepare for 1.11 release
  CHANGES
  docs/advanced.rst
  docs/using.rst
Labels: documentation

#1299 test: use underscore instead of dash in filenames
  .github/workflows/sanitizers.yml
  test/event_log.c
  test/install.c
  test/install_fixtures.c
  test/install_fixtures.h
  test/meson.build
  test/service.c
Labels: cleanup

#1300 minor cleanup for tests
  test/bundle.c
  test/install-content/payload-common.tar
  test/install-content/payload-special.tar
Labels: testing, cleanup

#1304 avoid using the term artifacts in the documentation
  README.rst
  docs/advanced.rst
  docs/basic.rst
  docs/index.rst
  docs/integration.rst
  docs/reference.rst
  docs/using.rst
  rauc.1
Labels: documentation

#1302 qemu-test-init: print backtrace for service threads if gdb is available
  qemu-test
  qemu-test-init
Labels: testing

#1292 Implement Actual Log Events for Configurable Event Logging
  src/install.c
  src/main.c
  src/mark.c
  test/install.c
Labels: enhancement

#1305 test/event_log: fix type mismatch
  test/event_log.c
Labels: testing, fixed

#1306 remove dashes from message IDs and add note in changelog
  CHANGES
  docs/advanced.rst
  src/event_log.c
  src/install.c
  src/main.c
  src/mark.c
  test/event_log.c
Labels: documentation
