Repository rauc/rauc, pull requests merged in 2024-01, with the labels that each got.

#1309 Ensure Only Bootable Slots Can be Marked
  src/bootchooser.c
  src/mark.c
  test/rauc.t
Labels: fixed

#1310 test/service: run service tests only as root
  test/service.c
Labels: fixed

#1320 src/bundle: fix double free
  src/bundle.c
Labels: fixed

#1319 Resolve Conflict With OpenSSL's built-in Check Purpose 'codesign'
  src/config_file.c
  src/signature.c
  test/bundle.c
  test/config_file.c
Labels: fixed

#1314 src/main: fix and add support for boot detection with rauc.external
  src/main.c
  test/rauc.t
Labels: fixed

#1324 docs/using: be more explicit on current pre-install hook implementation
  docs/using.rst
Labels: documentation

#1322 test/common: add helper to build a GPtrArray from a ;-separated string
  test/common.c
  test/common.h
Labels: testing

#1327 CHANGES: prepare for 1.12 development
  CHANGES
Labels: documentation

#1303 update_utils: refactor output stream
  include/update_utils.h
  src/update_handler.c
  src/update_utils.c
Labels: cleanup

#1321 refactor manifest checks
  include/manifest.h
  src/manifest.c
Labels: cleanup

#1318 build multiarch CI containers, use podman and run user-level tests
  .github/workflows/container.yml
  .github/workflows/style.yml
  .github/workflows/tests.yml
  test/Dockerfile
Labels: testing

#1332 src/nbd: initialize info_headers to NULL
  src/nbd.c
  test/rauc.t
Labels: fixed

#1328 improve structure of config and manifest reference
  docs/reference.rst
Labels: documentation

#1331 src/main: more explicit handling of rauc install user interruption
  src/main.c
Labels: enhancement

#1336 minor documentation fixes
  docs/integration.rst
  docs/reference.rst
Labels: documentation, fixed
