Repository rauc/rauc, pull requests merged in 2024-08, with the labels that each got.

#1478 improve log messages related to block hash indices
  src/hash_index.c
  test/update_handler.c
Labels: enhancement

#1482 minor docs cleanup
  docs/advanced.rst
  docs/basic.rst
  docs/index.rst
  docs/reference.rst
Labels: documentation

#1483 meson.build: derive dbuspolicydir from libdbus datadir
  meson.build
Labels: fixed

#1484 docs: integration: fix link syntax
  docs/integration.rst
Labels: documentation

#1474 move existing slot data directory to "unknown"
  include/slot.h
  src/install.c
  src/slot.c
  test/status_file.c
Labels: fixed

#1485 CHANGES: prepare for 1.12 release
  CHANGES
Labels: documentation

#1486 CHANGES: update release date
  CHANGES
Labels: documentation

#1489 Documentation: A few small FAQ fixes
  docs/faq.rst
Labels: documentation

#1481 test: create system files using the tmp_path pytest fixture
  test/conftest.py
  test/test_install.py
  test/test_service.py
Labels: testing

#1490 improve install messages
  src/install.c
  test/install.c
Labels: cleanup

#1491 update to uncrustify-0.79.0
  build-uncrustify.sh
  test/bundle.c
  test/install.c
  test/nbd.c
Labels: cleanup

#1492 test: fix typos
  test/test_bundle.py
  test/update_handler.c
Labels: testing, fixed

#1493 data: fix BUNDLE_VERSION variable in catalog entry
  data/rauc.catalog
Labels: fixed

#1497 CHANGES: prepare for 1.13 release
  CHANGES
Labels: documentation

#1498 link the DCO and fix some documentation typos
  CHANGES
  docs/contributing.rst
  docs/reference.rst
Labels: documentation, cleanup

#1494 test: prepare system files with config for no_service tests
  test/conftest.py
  test/test_mark.py
  test/test_status.py
Labels: testing

#1504 minor cleanups: add comment for check_manifest_bundled and fix format migration anchor in docs
  docs/integration.rst
  src/manifest.c
Labels: documentation, cleanup

#1503 improve rauc info/status/help output by avoiding tabs
  src/main.c
  test/test_info.py
Labels: cleanup

#1505 expose manifest meta-data in handler environment
  include/shell.h
  meson.build
  src/install.c
  src/main.c
  src/shell.c
  test/adaptive-test.conf
  test/bin/postinstall.sh
  test/bin/preinstall.sh
  test/conftest.py
  test/test_install.py
Labels: enhancement

#1506 expose manifest meta-data in install-check hook environment
  docs/reference.rst
  include/utils.h
  src/install.c
  src/update_handler.c
  src/utils.c
  test/conftest.py
  test/test_install.py
Labels: enhancement, testing

#1508 add test case for PKCS#11 decryption
  test/conftest.py
  test/test_info.py
Labels: testing

#1509 src/bundle: fix hash_index fd close handling
  src/bundle.c
  src/hash_index.c
  test/conftest.py
  test/hash_index.c
  test/test_bundle.py
Labels: fixed
