Repository rauc/rauc, pull requests merged in 2024-07, with the labels that each got.

#1454 src/bundle: fix assert handling in uint64 read/write functions
  src/bundle.c
Labels: fixed

#1456 src/main: fix wrong log field numbers in r_event_log_booted
  src/main.c
Labels: fixed

#1465 docs/requirements.txt: update to current versions
  docs/requirements.txt
Labels: documentation, dependencies

#1463 src/main: fix leaking strings when printing hooks with 'rauc info'
  src/main.c
Labels: fixed

#1462 Memory handling fixes for casync archive conversion
  src/bundle.c
Labels: fixed

#1421 src/update_handler: fix double close on ubivol descriptor
  src/update_handler.c
Labels: fixed

#1464 prepare for 1.12 release
  CHANGES
  docs/conf.py
  meson.build
Labels: documentation

#1468 fix leak in tests and run the full test suite with ASAN and UBSAN
  .github/workflows/sanitizers.yml
  qemu-test-init
  test/boot_switch.c
  test/update_handler.c
Labels: testing

#1471 Add missing "PRIORITY" field to structured logging arrays
  include/event_log.h
  src/event_log.c
  src/install.c
  src/main.c
  test/event_log.c
Labels: fixed

#1400 semantic version comparison
  docs/reference.rst
  include/config_file.h
  include/install.h
  include/utils.h
  src/config_file.c
  src/install.c
  src/main.c
  src/service.c
  src/utils.c
  test/common.c
  test/common.h
  test/config_file.c
  test/install.c
  test/install_fixtures.c
  test/install_fixtures.h
  test/service.c
  test/utils.c
Labels: enhancement

#1472 CHANGES: prepare for 1.12 release
  CHANGES
Labels: documentation

#1473 src/nbd: warn about slow installation when using HTTP/1
  src/nbd.c
Labels: enhancement

#1475 test/install: avoid false positive in coverity
  test/install.c
Labels: testing, fixed
