Repository rauc/rauc, pull requests merged in 2024-05, with the labels that each got.

#1406 test/gen_payload_tar.py: format with ruff
  test/gen_payload_tar.py
Labels: testing, cleanup

#1410 test/Dockerfile: install pytest and pydbus
  test/Dockerfile
Labels: testing

#1398 Fix PKCS11 URI handling in /etc/rauc/system.conf
  src/utils.c
Labels: fixed

#1412 Use meson TAP protocol parser
  qemu-test-init
  test/bundle.c
  test/dm.c
  test/hash_index.c
  test/install.c
  test/install_fixtures.c
  test/meson.build
  test/nbd.c
  test/network.c
Labels: testing

#1401 Replace sharness-based test suite by pytest
  .github/workflows/style.yml
  docs/advanced.rst
  docs/contributing.rst
  tap-t
  test/.ruff.toml
  test/conftest.py
  test/helper.py
  test/meson.build
  test/rauc.t
  test/sharness.sh
  test/test_bundle.py
  test/test_cmdline.py
  test/test_convert.py
  test/test_encrypt.py
  test/test_extract.py
  test/test_info.py
  test/test_install.py
  test/test_mark.py
  test/test_mount.py
  test/test_replace_signature.py
  test/test_resign.py
  test/test_service.py
  test/test_sign.py
  test/test_status.py
  test/test_verify.py
  test/test_write_slot.py
Labels: testing

#1375 Add extra-mkfs-opts to allow customising filesystem format options
  docs/reference.rst
  include/slot.h
  include/utils.h
  src/config_file.c
  src/slot.c
  src/update_handler.c
  test/config_file.c
Labels: enhancement

#1415 test/boot_switch: fix out of bound read
  test/boot_switch.c
Labels: testing, fixed

#1417 src/signature: add helper function to access a GBytes via a BIO
  src/signature.c
Labels: cleanup

#1418 avoid possible OOB read in bootchooser backends
  include/utils.h
  src/bootchooser.c
  src/utils.c
  test/utils.c
Labels: fixed, cleanup

#1424 qemu-test-init: fix support for faketime
  qemu-test-init
Labels: testing, fixed

#1423 simplify dbus fixtures
  test/conftest.py
  test/test_install.py
  test/test_mark.py
  test/test_service.py
  test/test_status.py
Labels: testing, cleanup

#1425 use a temporary workdir during bundle creation
  docs/faq.rst
  src/bundle.c
  test/install-content/manifest.raucm
  test/install-content/manifest.raucm.crypt
Labels: enhancement

#1434 docs/requirements.txt: update to current versions
  docs/requirements.txt
Labels: documentation, dependencies

#1432 test/conftest: skip faketime tests if a sanitizer is enabled
  test/conftest.py
Labels: testing
