Repository rauc/rauc, pull requests merged in 2024-09, with the labels that each got.

#1512 test/conftest: fix service shutdown
  test/conftest.py
Labels: testing

#1511 src/utils: declare variables at the first assignment
  src/utils.c
Labels: cleanup

#1507 check if encryption recipient cert file containes at least one certificate
  src/signature.c
  test/test_encrypt.py
Labels: fixed

#1515 meson.build: sort file lists
  meson.build
  test/meson.build
Labels: cleanup

#1514 test/Dockerfile: add tree utility
  test/Dockerfile
Labels: testing

#1510 minor updates to the test infrastructure
  qemu-test-init
  test/conftest.py
  test/helper.py
Labels: testing

#1520 update to codecov-action@v4
  .github/workflows/tests.yml
Labels: testing

#1516 test/conftest: start dbus-daemon directly instead of using dbus-launch
  test/conftest.py
Labels: testing, fixed

#1521 add codecov yaml configuration file
  .codecov.yaml
Labels: testing

#1526 qemu-test-init: remove potential symlink at /etc/resolv.conf
  qemu-test-init
Labels: testing, fixed

#1527 use ubuntu-24.04 for CI and simplify workflows
  .github/workflows/tests.yml
Labels: testing, cleanup

#1518 src/nbd: show stats even if the NBD server exits with an error
  src/nbd.c
Labels: enhancement
