Repository rauc/rauc, pull requests merged in 2024-04, with the labels that each got.

#1372 minor simplifications for memory management and tests
  src/bootchooser.c
  src/update_handler.c
  test/manifest.c
Labels: cleanup

#1373 qemu-test-init: fix git repo access and simplify service handling
  qemu-test-init
Labels: enhancement, testing

#1374 fix some memory leaks in the NBD server and enable asan for the tests
  .github/workflows/sanitizers.yml
  src/nbd.c
Labels: testing, fixed

#1370 src/config_file: add a hint that max-bundle-download-size is not used for streaming
  docs/reference.rst
  src/config_file.c
Labels: documentation

#1376 test/rauc.t: test faketime before relying on it
  test/rauc.t
Labels: testing

#1377 fix minor memory leaks in the D-Bus service and related tests
  .github/workflows/sanitizers.yml
  qemu-test
  qemu-test-init
  src/install.c
  src/service.c
  test/asan.supp
  test/boot_raw_fallback.c
  test/boot_switch.c
  test/service.c
Labels: testing, fixed

#1378 .github/workflows: update to actions/checkout@v4
  .github/workflows/codeql.yml
  .github/workflows/container.yml
  .github/workflows/coverity.yml
  .github/workflows/sanitizers.yml
  .github/workflows/scan-build.yml
  .github/workflows/style.yml
  .github/workflows/tests.yml
Labels: testing

#1379 test/Dockerfile: add acl to control access to coverage files in qemu
  test/Dockerfile
Labels: testing

#1380 fix leaks discovered via shell based tests
  include/utils.h
  src/bundle.c
  src/context.c
  src/main.c
  src/utils.c
  test/common.c
Labels: fixed

#1384 manifest: ensure that size always defaults to -1 in RaucImage
  include/checksum.h
  include/manifest.h
  src/main.c
  src/manifest.c
  test/boot_raw_fallback.c
  test/boot_switch.c
  test/common.c
  test/manifest.c
  test/update_handler.c
Labels: testing, fixed

#1381 qemu-test-init: fix coverage for nbd helper
  qemu-test-init
Labels: testing

#1390 Fix several typos
  docs/integration.rst
  test/bin/barebox-state
  test/bin/fw_printenv
  test/bin/fw_setenv
  test/bootchooser.c
Labels: cleanup

#1396 docs/requirements.txt: update to current versions
  docs/requirements.txt
Labels: documentation

#1394 README.rst: update license date to 2024
  README.rst
Labels: documentation

#1397 ignore SIGPIPE to handle broken pipes explicitly
  src/context.c
  src/nbd.c
Labels: testing, fixed

#1392 Fix slot skipping (install-same) handling twice
  src/install.c
  test/install.c
  test/test-install-same-false.conf
Labels: fixed
