Repository rauc/rauc, pull requests merged in 2024-11, with the labels that each got.

#1547 test/test_extract: fix test for crypt bundle extraction
  test/test_extract.py
Labels: testing

#1551 artifacts: fix repo type check
  src/artifacts.c
  test/artifacts.c
Labels: fixed

#1552 .github/workflows/tests: test with and without service and gpt features
  .github/workflows/tests.yml
Labels: testing

#1555 Extend and Enhance Various Test Cases
  test/conftest.py
  test/context.c
  test/event_log.c
  test/meson.build
  test/test_cmdline.py
  test/test_mark.py
  test/test_service.py
  test/test_status.py
  test/test_write_slot.py
Labels: testing

#1549 src/signature: fix CMS debug output check
  src/signature.c
Labels: fixed

#1558 README.rst: document python3-pytest and -pydbus as test dependencies
  README.rst
Labels: documentation

#1560 use Ubuntu 24.04 to build the CI container and add mmc-utils
  .github/workflows/container.yml
  test/Dockerfile
Labels: testing

#1557 support locating system.conf in /usr and /run
  data/rauc.service.in
  docs/examples.rst
  docs/integration.rst
  docs/reference.rst
  docs/using.rst
  rauc.1
  src/context.c
Labels: enhancement

#1561 test boot-emmc slots in QEMU
  .github/workflows/tests.yml
  .gitignore
  qemu-test
  qemu-test-init
  test/conftest.py
  test/test_write_slot.py
Labels: testing

#1563 config_file: handle empty config file specially
  include/config_file.h
  src/config_file.c
  src/context.c
Labels: enhancement

#1565 install: define RAUC_SYSTEM_VARIANT for handlers
  docs/reference.rst
  src/install.c
Labels: enhancement

#1567 tests: Make GRUB env handling more consistent and update qemu-test doc, etc.
  docs/contributing.rst
  docs/using.rst
  qemu-test-init
  test/adaptive-test.conf
  test/bin/postinstall.sh
  test/bin/preinstall.sh
  test/conftest.py
  test/crypt-test.conf
  test/minimal-test.conf
  test/system.conf
  test/test.conf
  test/test_install.py
  test/test_mark.py
  test/test_service.py
  test/test_status.py
  test/test_write_slot.py
Labels: testing, cleanup

#1572 test: replace minimal-test.conf with dynamic config generation
  test/conftest.py
  test/minimal-test.conf
  test/test_install.py
Labels: testing, cleanup

#1575 test/test_bundle: update formatting to ruff 0.8.1
  test/test_bundle.py
Labels: testing

#1573 docs: some documentation updates and fixes
  docs/advanced.rst
  docs/contributing.rst
  docs/integration.rst
  docs/reference.rst
  docs/using.rst
Labels: documentation

#1577 replace some fixed configuration files with dynamic config generation
  test/adaptive-test.conf
  test/conftest.py
  test/crypt-test.conf
  test/minimal-desync-test.conf
  test/test_convert.py
Labels: testing, cleanup
