Repository rauc/rauc, pull requests merged in 2024-10, with the labels that each got.

#1531 src/main: handle empty bootname in r_event_log_booted()
  src/main.c
Labels: fixed

#1536 meson: fix test dependencies on rauc binary
  meson.build
  test/meson.build
Labels: testing

#1535 qemu-test: enable eMMC driver
  qemu-test
Labels: testing

#1537 fix scan-build report
  .github/workflows/scan-build.yml
  scan-build
Labels: testing

#1301 add support for artifacts (separate applications/containers/data files)
  CHANGES
  docs/basic.rst
  docs/examples.rst
  docs/integration.rst
  docs/reference.rst
  docs/scenarios.rst
  docs/terminology.rst
  docs/using.rst
  include/artifacts.h
  include/config_file.h
  include/install.h
  include/manifest.h
  include/utils.h
  meson.build
  qemu-test-init
  qemu-test-rauc-config
  src/artifacts.c
  src/bundle.c
  src/config_file.c
  src/de.pengutronix.rauc.Installer.xml
  src/install.c
  src/main.c
  src/manifest.c
  src/service.c
  src/utils.c
  test/artifacts.c
  test/bundle.c
  test/common.c
  test/common.h
  test/config_file.c
  test/conftest.py
  test/gen_payload_tar.py
  test/install-content/payload-common.tar
  test/install-content/payload-medium-data-size-a.tar.gz
  test/install-content/payload-medium-data-size-b.tar.gz
  test/install.c
  test/install_fixtures.c
  test/manifest.c
  test/meson.build
  test/minimal-test.conf
  test/test.conf
  test/test_artifacts.py
Labels: enhancement

#1540 .github/workflows/tests: upload coverage separately for service=true/false
  .github/workflows/tests.yml
Labels: testing

#1544 .github/workflows/tests: fix trailing whitespace
  .github/workflows/tests.yml
Labels: testing

#1546 CHANGES: prepare for 1.13 release
  CHANGES
Labels: documentation

#1528 src/bundle: gracefully abort remote bundle install if support is disabled
  include/bundle.h
  src/bundle.c
Labels: fixed

#1523 src/manifest: throw parser error for invalid slot hook combination
  include/manifest.h
  src/bundle.c
  src/manifest.c
  test/manifest.c
Labels: enhancement
