Repository rauc/rauc, pull requests merged in 2024-02, with the labels that each got.

#1334 src/nbd: fix nbd server 'no more retries' handling
  src/nbd.c
Labels: fixed

#1342 Minor Cleanups For Install Error Codes
  include/install.h
  src/install.c
Labels: cleanup

#1343 Fixes for Event Logging
  src/main.c
Labels: fixed

#1355 document manifest syntax for image variants
  docs/reference.rst
Labels: documentation

#1340 src/install: remove redundant installation rejection log message
  src/install.c
Labels: fixed

#1344 Slightly Stricter Style Checks
  .uncrustify.cfg
  src/bundle.c
  src/main.c
  src/nbd.c
  test/dm.c
  test/fakerand.c
  test/service.c
  test/update_handler.c
  test/utils.c
Labels: cleanup

#1357 CodeQL Workflow: Update and Filter Results
  .github/workflows/codeql.yml
Labels: testing

#1356 src/update_handler: update link to emmc boot partition
  src/update_handler.c
Labels: documentation, fixed
