Repository rauc/rauc, pull requests merged in 2025-01, with the labels that each got.

#1589 Add support for TFTP
  README.rst
  src/bundle.c
Labels: enhancement

#1592 test: re-format pytest tests with ruff 0.9.1
  test/test_extract.py
  test/test_info.py
  test/test_replace_signature.py
  test/test_resign.py
  test/test_verify.py
Labels: testing, cleanup

#1594 improve qemu-test docs
  docs/contributing.rst
  docs/using.rst
Labels: documentation

#1598 src/bootchooser: fix spelling typo in code
  src/bootchooser.c
Labels: cleanup

#1597 src/emmc: Error-Out for invalid boot partition configuration and use more explicit errors
  include/emmc.h
  src/emmc.c
  src/update_handler.c
  test/test_write_slot.py
Labels: fixed, cleanup

#1600 simplify control flow in mark_run
  src/mark.c
Labels: cleanup

#1601 refactor service startup for pytest-based tests
  test/conftest.py
Labels: testing, cleanup

#1542 Add -C option to overwrite config file parameters
  docs/reference.rst
  include/context.h
  rauc.1
  src/config_file.c
  src/context.c
  src/main.c
  test/test_info.py
Labels: enhancement

#1585 Check the slot status in case of reinstalling of failed slot
  src/install.c
Labels: fixed

#1602 include/install.h: remove left-over do_install_network() prototype
  include/install.h
Labels: cleanup

#1604 CHANGES: prepare for 1.13 release
  CHANGES
Labels: documentation

#1609 src/main: fix leaking error
  src/main.c
Labels: fixed

#1584 Add option to prevent fallback
  docs/reference.rst
  include/config_file.h
  src/config_file.c
  src/mark.c
  test/conftest.py
  test/test_mark.py
Labels: enhancement

#1614 .github/workflows/scan-build: update to actions/upload-artifact@v4
  .github/workflows/scan-build.yml
Labels: fixed, build
