Repository rauc/rauc, pull requests merged in 2025-06, with the labels that each got.

#1721 clarify the write-slot use-case and simplify control flow
  rauc.1
  src/main.c
Labels: cleanup

#1720 de.pengutronix.rauc.Installer.xml: add and use CC0-1.0 license
  LICENSES/CC0-1.0.txt
  src/de.pengutronix.rauc.Installer.xml
Labels: cleanup

#1736 Error handling and usability improvements around (eMMC) bootloader updates
  docs/reference.rst
  src/config_file.c
  src/main.c
  src/update_handler.c
  test/config_file.c
Labels: enhancement

#1739 docs/reference: more explicit documentation for binary suffixed strings
  docs/reference.rst
Labels: documentation

#1733 context and progress handling improvements for development
  include/context.h
  src/context.c
Labels: cleanup

#1745 docs/requirements.txt: update to current versions
  docs/requirements.txt
Labels: documentation, dependencies

#1740 add new 'size-limit' option for type 'boot-emmc'
  docs/faq.rst
  docs/reference.rst
  include/slot.h
  src/config_file.c
  src/update_handler.c
  test/test_write_slot.py
Labels: enhancement

#1747 signature: prepare for multiple signature support
  src/signature.c
  test/signature.c
Labels: cleanup

#1748 test/Dockerfile: add python3-pyasn1 for testing
  test/Dockerfile
Labels: testing
