Repository rauc/rauc, pull requests merged in 2025-03, with the labels that each got.

#1643 manifest: add a min-rauc-version
  docs/reference.rst
  include/manifest.h
  meson.build
  src/manifest.c
  test/test_bundle.py
Labels: enhancement

#1645 add support for requiring a specific manifest hash during installation
  docs/reference.rst
  include/install.h
  src/install.c
  src/main.c
  src/service.c
  test/test_install.py
Labels: enhancement

#1650 src/manifest: ignore the rollout section for now
  src/manifest.c
  test/test_bundle.py
Labels: enhancement

#1652 test/stats: remove compatibility defines for glib < 2.58
  test/stats.c
Labels: cleanup

#1651 CHANGES: prepare for 1.14 release
  CHANGES
Labels: documentation

#1655 src/manifest: add argument checks
  src/manifest.c
Labels: cleanup

#1656 nbd: add explicit handling of HTTP codes 204 and 304
  include/nbd.h
  src/nbd.c
  test/nbd.c
  test/nginx.conf
Labels: enhancement

#1653 utils: add function to format a duration as a human readable string
  include/utils.h
  src/utils.c
  test/utils.c
Labels: enhancement

#1662 src/nbd: avoid a false positive in coverity
  src/nbd.c
Labels: cleanup

#1667 advanced.rst: fix event-log anchor
  docs/advanced.rst
Labels: documentation, fixed

#1668 src/mount: simplify control flow
  src/mount.c
Labels: cleanup

#1659 src/install: ensure converted pointer is valid before dereferencing
  src/install.c
Labels: bug, fixed

#1670 docs/reference: mention rollout section in the manifest
  docs/reference.rst
Labels: documentation, fixed

#1677 src/bootloaders/custom: don't auto-free GError r_custom_get_current_bootname()
  src/bootloaders/custom.c
Labels: fixed
