Repository rauc/rauc, pull requests merged in 2025-02, with the labels that each got.

#1618 docs/requirements.txt: update to current versions
  docs/requirements.txt
Labels: documentation, dependencies

#1500 add support for composefs artifacts
  .github/workflows/tests.yml
  CHANGES
  docs/integration.rst
  docs/reference.rst
  include/artifacts.h
  include/artifacts_composefs.h
  meson.build
  meson_options.txt
  qemu-test-init
  src/artifacts.c
  src/artifacts_composefs.c
  src/bundle.c
  subprojects/composefs.wrap
  test/bundle.c
  test/common.c
  test/common.h
  test/conftest.py
  test/install.c
  test/install_fixtures.c
  test/meson.build
  test/test_artifacts.py
Labels: enhancement

#1619 src/update_handler: add detailed progress when installing block hash index images
  src/update_handler.c
Labels: enhancement

#1620 docs: update links and warn against simply using test/openssl-ca-create.sh
  docs/advanced.rst
  test/openssl-ca-create.sh
Labels: documentation

#1621 context: add support for a system version
  docs/reference.rst
  include/context.h
  src/context.c
  test/bin/systeminfo.sh
  test/context.c
Labels: enhancement

#1622 test/Dockerfile: add python3-requests
  test/Dockerfile
Labels: enhancement, testing

#1623 src: simplify unchanged progress update skipping
  src/context.c
  src/update_handler.c
  src/update_utils.c
Labels: cleanup

#1628 Minor Update handler cleanups
  src/update_handler.c
Labels: cleanup

#1624 test: improve http tests
  test/conftest.py
  test/nginx_backend.py
  test/test_http.py
Labels: enhancement, testing

#1627 src: simplify and fix NFS (external) boot detection
  src/context.c
  src/install.c
  test/context.c
Labels: fixed

#1626 Feature/pre post install pass transaction
  src/install.c
Labels: cleanup

#1639 test/Dockerfile: add python3-dasbus for testing
  test/Dockerfile
Labels: testing

#1633 avoid GDestroyNotify cast for g_clear_pointer
  src/artifacts.c
  src/manifest.c
Labels: cleanup

#1636 Split backends into dedicated files
  include/bootchooser.h
  meson.build
  src/bootchooser.c
  src/bootloaders/barebox.c
  src/bootloaders/barebox.h
  src/bootloaders/custom.c
  src/bootloaders/custom.h
  src/bootloaders/efi.c
  src/bootloaders/efi.h
  src/bootloaders/grub.c
  src/bootloaders/grub.h
  src/bootloaders/uboot.c
  src/bootloaders/uboot.h
Labels: cleanup

#1634 src/mount: open /dev/loop* readonly
  src/mount.c
Labels: fixed

#1644 rename SECURITY.rst to SECURITY.md
  SECURITY.md
Labels: documentation

#1642 make maximum signature size configurable
  docs/reference.rst
  include/config_file.h
  src/bundle.c
  src/config_file.c
  test/config_file.c
Labels: fixed

#1647 src/bundle: add printout if crated signature size exceeds sanity default
  src/bundle.c
Labels: enhancement

#1640 src/service: fix leak of RaucBundleAccessArgs for InspectBundle
  include/bundle.h
  src/service.c
  test/conftest.py
Labels: fixed

#1632 require glib version 2.64.0
  meson.build
Labels: compatibility

#1641 test: migrate from pydbus to dasbus
  README.rst
  test/conftest.py
  test/test_mark.py
Labels: cleanup
