Repository rauc/rauc, pull requests merged in 2025-05, with the labels that each got.

#1706 src/update_handler: fix memory leak on G_IO_ERROR_NO_SPACE in clear_slot()
  src/update_handler.c
Labels: fixed

#1710 Add allowed-signer-cns parameter to keyring section
  docs/reference.rst
  include/config_file.h
  include/signature.h
  src/config_file.c
  src/signature.c
  test/config_file.c
  test/signature.c
Labels: enhancement

#1702 docs/examples: fix grub.cfg example
  docs/examples.rst
Labels: documentation
