Repository rauc/rauc, pull requests merged in 2025-08, with the labels that each got.

#1766 run test suite for various distributions
  .github/workflows/tests.yml
  README.rst
  src/context.c
  test/test_http.py
Labels: testing, fixed

#1768 .github/workflows/tests: don't try to print old logfile locations
  .github/workflows/tests.yml
Labels: testing

#1763 config_file: implement default_config using parse_config
  include/config_file.h
  src/config_file.c
  src/context.c
Labels: enhancement, cleanup

#1769 CHANGES: prepare for 1.15 release
  CHANGES
  docs/reference.rst
Labels: documentation

#1771 src/config_file: clear 'variant_data' more consistently
  src/config_file.c
Labels: cleanup

#1780 qemu-test-init: wipe old logs to avoid confusion
  qemu-test-init
Labels: testing
