Repository rauc/rauc, pull requests merged in 2025-04, with the labels that each got.

#1683 docs: use pygments Devicetree lexer
  docs/conf.py
  docs/extensions/lexer/DtsLexer.py
  docs/extensions/lexer/__init__.py
  docs/integration.rst
Labels: documentation, cleanup

#1682 CHANGES: prepare for 1.14 release
  CHANGES
Labels: documentation

#1685 docs/integration: document tar requirements for artifact repos
  docs/integration.rst
Labels: documentation

#1654 send headers for InspectBundle and add support for a system-version HTTP header
  docs/reference.rst
  include/bundle.h
  include/nbd.h
  qemu-test-init
  src/bundle.c
  src/install.c
  src/main.c
  src/nbd.c
  src/service.c
  test/conftest.py
  test/meson.build
  test/nginx_backend.py
  test/test_http.py
Labels: enhancement

#1689 docs/integration: clarify the RAUC_BUNDLE_FORMAT variable
  docs/integration.rst
Labels: documentation

#1692 rauc.1: add missing 'rauc install' arguments
  rauc.1
Labels: documentation

#1697 fix OpenSSL 3.5 compatibility
  src/context.c
  src/signature.c
Labels: fixed

#1690 meson: add support for building without OpenSSL engine support
  meson.build
  meson_options.txt
  src/signature.c
Labels: enhancement

#1695 src/nbd:set groups of child process
  src/nbd.c
Labels: enhancement

#1699 some minor cleanups
  include/utils.h
  src/nbd.c
  src/service.c
Labels: cleanup

#1703 test/install: simplify install_cleanup
  test/install.c
Labels: testing, cleanup
